"""Ingebakken DNP QW410 DEVMODE-referentieprofielen.

Eenmalig vastgelegd op een correct ingestelde QW410 (CUTTERCONTROL:
  4x6_nocut = CUT_STANDARD  (geen cut)
  4x6_cut   = CUT_2INCH     (2-inch cut, 3 stripjes)
Wordt bij een DNP QW410 automatisch weggeschreven als het profiel op die
PC nog niet is vastgelegd (bestaande captures blijven ongemoeid).
Gegenereerd; niet met de hand aanpassen.
"""
import base64

_B64 = {
    "4x6_nocut": (
        "RABQAC0AUQBXADQAMQAwACAAKABLAG8AcABpAGUAIAAyACkAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAEEAwbcAFgEQ++BBwEAsAASBi8EZAABAA8ALAECAAEALAECAAEAKAA0AHgANgApAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAQAAAAAAAAACAAAAAgAAAAEAAAD/////AAAAAAAAAAAAAAAAAAAAAERJTlUiAHAB"
        "zAOMABaepusAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAQAAAAEAAAAA"
        "AAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAQAAU01USgAAAAAQAGABRABQAC0AUQBXADQAMQAw"
        "AAAASW5wdXRCaW4ARk9STVNPVVJDRQBSRVNETEwAVW5pcmVzRExMAE9yaWVudGF0aW9uAFBPUlRS"
        "QUlUAFJlc29sdXRpb24AT3B0aW9uMQBQcmludE1hcmdpbgBNYXJnaW5PZmYAT1ZFUkNPQVRUWVBF"
        "AE9QVFlQRV9MVVNURVIAUFJJTlRCVUZGQ09OVFJPTABQQkNfTk9OQ0xFQVIAQ1VUVEVSQ09OVFJP"
        "TABDVVRfU1RBTkRBUkQASGlnaERlbnNpdHlNb2RlAFNURF9ERU5TAERlY3VybENvbnRyb2wAREVD"
        "VVJMX0FVVE8AUGFwZXJTaXplAENaXzQweDYwAE1lZGlhVHlwZQBTVEFOREFSRABDb2xvck1vZGUA"
        "MjRicHAASGFsZnRvbmUASFRfUEFUU0laRV9TVVBFUkNFTExfTQAAAAAAAAAAAAAAAAAAAIwAAABU"
        "RlNNBAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA"
        "AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAfAAAAAQAA"
        "AAAAAAAAAAAAAAAAAAEAAAACAAAA"
    ),
    "4x6_cut": (
        "RABQAC0AUQBXADQAMQAwACAAKABLAG8AcABpAGUAIAAyACkAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAEEAwbcAFgEQ++BBwEAsAASBi8EZAABAA8ALAECAAEALAECAAEAKAA0AHgANgApAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAQAAAAAAAAACAAAAAgAAAAEAAAD/////AAAAAAAAAAAAAAAAAAAAAERJTlUiAHAB"
        "zAOMABaepusAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAQAAAAEAAQAA"
        "AAIAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAQAAU01USgAAAAAQAGABRABQAC0AUQBXADQAMQAw"
        "AAAASW5wdXRCaW4ARk9STVNPVVJDRQBSRVNETEwAVW5pcmVzRExMAE9yaWVudGF0aW9uAFBPUlRS"
        "QUlUAFJlc29sdXRpb24AT3B0aW9uMQBQcmludE1hcmdpbgBNYXJnaW5PZmYAT1ZFUkNPQVRUWVBF"
        "AE9QVFlQRV9MVVNURVIAUFJJTlRCVUZGQ09OVFJPTABQQkNfTk9OQ0xFQVIAQ1VUVEVSQ09OVFJP"
        "TABDVVRfMklOQ0gASGlnaERlbnNpdHlNb2RlAFNURF9ERU5TAERlY3VybENvbnRyb2wAREVDVVJM"
        "X0FVVE8AUGFwZXJTaXplAENaXzQweDYwAE1lZGlhVHlwZQBTVEFOREFSRABDb2xvck1vZGUAMjRi"
        "cHAASGFsZnRvbmUASFRfUEFUU0laRV9TVVBFUkNFTExfTQAAAAAAAAAAAAAAAAAAAAAAAIwAAABU"
        "RlNNBAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAA"
        "AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAfAAAAAQAA"
        "AAEAAAAAAAAAAAAAAAEAAAACAAAA"
    ),
}

DNP_REF = {k: base64.b64decode(v) for k, v in _B64.items()}
